blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/keeweb/keeweb/discussions
    about: A place to ask and answer questions or discuss different topics
  - name: Twitter
    url: https://twitter.com/kee_web
    about: Ask a quick question there if you like Twitter more
